version: '3.1'
services:
  mongo:
    build: ./mongodb_rs
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: jobizil 
      MONGO_INITDB_ROOT_PASSWORD: hello
      MONGO_INITDB_DATABASE: mainstack
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - '27018:27017'
